### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by dharmendrakariya** [kerberos-io/hub#3]
I see you are adding helm charts manually, why dont just use github action helm releaser and keep seperate repo for helm repo.

Just a suggestion.

**Comment by cedricve** [comment]
great feedback ! we will addd that to our board. thanks

**Comment by dharmendrakariya** [comment]
https://helm.sh/docs/howto/chart_releaser_action/

**Comment by cedricve** [comment]
@dharmendrakariya  thanks according your feedback we moved it to a seperate repo https://github.com/kerberos-io/helm-charts Thank youuu! ;)
